
remote_theme: tuur29/pages-themes-cayman
title: Žofín ForestGEO data
description: Open sample of dataset from the oldest natural reservation in Central Europe.
show_downloads: true
darkmode: false

hide_first_title: true # Useful if README.md is used on both github and pages

colors:
    gradient_left: "#FDE725FF"
    gradient_right: "#440145FF"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#155799" # this default to gradient_color
buttons:
      zip_url: https://naturalforests.cz/
      zip_title: View team
      zip_hide: false
      tar_url: https://forestgeo.si.edu/sites/europe/zofin
      tar_title: View plot details
      tar_hide: false
      github_hide: false # hides "View on Github"
