
# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        sample dataset
relative_permalinks: true

# Setup
title:            Žofín
tagline:          'A Jekyll theme'
description:      'A sample daset of data collected by Blue Cat team on ...
url:              https://vukoz-oel.github.io/bluecat-data-pool/
baseurl:          /

author:
  name:           'mmm'
  url:            www

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde